# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('ctznno', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
            ],
        ),
    ]
