# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Criminals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=50)),
                ('crime_desc', models.CharField(max_length=200)),
                ('crime_date', models.DateTimeField()),
                ('crime_addr', models.CharField(max_length=50)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(max_length=50)),
                ('victim_desc', models.CharField(max_length=200)),
                ('victim_addr', models.CharField(max_length=50)),
                ('victim_age', models.IntegerField()),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Criminals.crime')),
            ],
        ),
    ]
