# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminals', '0002_crime_victim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='id',
        ),
        migrations.AddField(
            model_name='crime',
            name='case_no',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
