# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Criminals', '0006_auto_20160829_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime', to='Criminals.Criminal'),
        ),
    ]
