# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Criminals', '0007_auto_20160829_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=50)),
                ('crime_addr', models.CharField(max_length=50)),
                ('full_report', models.CharField(max_length=200)),
                ('reported_by', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='crime',
            name='criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime', to='Criminals.Criminal'),
        ),
    ]
